### ISSUE TITLE
Import fails if no `identityFields` option set

### ISSUE THREAD

**Issue by alexjreich** [nxus/data-loader#1]
The README makes this sound optional, but the import fails if this isn’t set to a valid field.

**Note**: My data set didn’t include an `id` field.  If not set, it should probably just insert the object rather than trying to update based on `criteria`.

**Comment by loppear** [comment]
Agreed this should be supported, probably/possibly only if we add in the `truncate` option as well that we discussed offline a while back. While it's perhaps reasonable to support collections that should just be appended to with new data, I'd be worried about re-submitting the same data upload and getting duplicates, so I'd rather the user needs to either provide the `truncate` option, or specify that most/all fields make up the "identity" for these append cases.

**Comment by alexjreich** [comment]
I would assume truncate, and specify `false` if you want to re-add everything if no `id`.

**Comment by loppear** [comment]
Hmm, not totally comfortable with the default behavior if you forget to add the config is to wipe out data. I'm suggesting a useful error message if you provide neither `identityFields` or `truncate=true`.
